#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication ./Allrun.pre

#-- Run on single processor
#runApplication $(getApplication)

# Decompose
runApplication decomposePar -allRegions

# Run
#runParallel $(getApplication)
$(getApplication) > log &
# Reconstruct
#runApplication reconstructPar -allRegions

#------------------------------------------------------------------------------
